version: "3"
services:
  frontend:
    build:
      context: ./packages/react-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build:
      context: ./packages/express-backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - "./packages/express-backend/.env"
