name: CI

on:
  push:
    branches:
      - master

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies(Frontend)
        run: npm install
        working-directory: packages/react-frontend

      - name: Install Dependencies (Backend)
        run: npm install
        working-directory: packages/express-backend

      - name: Build (Frontend)
        run: npm run build
        working-directory: packages/react-frontend

      #- name: Build
      #  run: npm run build

      - name: Run Tests (Frontend)
        run: npm test
        working-directory: packages/react-frontend
